# Generated by Django 5.1.2 on 2024-12-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_gullar_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gullar',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='gul matni'),
        ),
        migrations.AlterField(
            model_name='gullar',
            name='title',
            field=models.CharField(max_length=250, verbose_name='gul nomi'),
        ),
    ]
